-- Migration: Drop unused intercom_tenant_mapping table
-- Generated by: PlanetScale Insights Schema Suggestion
-- Reason: Unused table detected by PlanetScale Insights
-- Date: $(date +%Y-%m-%d)

-- Drop the unused intercom_tenant_mapping table
DROP TABLE `planetscale`.`intercom_tenant_mapping`;